name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install dependences
        run: sh ./contrib/ubuntu.sh
      - run: cargo check --workspace --all-targets --all-features

  projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - -p lightning-client

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install dependences
        run: sh ./contrib/ubuntu.sh
      - run: cargo check ${{ matrix.args }}

  platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
      matrix:
        os:
          - macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install dependences
        run: sh ./contrib/${{ matrix.os }}.sh
      - run: cargo check --workspace --all-targets --all-features

  toolchains:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - 1.70.0

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install dependences
        run: sh ./contrib/ubuntu.sh
      - run: cargo check --workspace --all-targets --all-features
