//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

/// Record of user balance changes

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,

    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub user_pubkey: Vec<u8>,

    pub invoice_id: Option<i64>,

    /// user current balance in msats
    pub balance: i64,
    /// balance change
    pub change: i64,

    pub source: String,

    pub note: String,

    /// data create time
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
